### ISSUE TITLE
Can you tell us how to register new fingerprint at time of registering user.

### ISSUE THREAD

**Issue by aj-techsoul** [nurkarim/zkteco-sdk-php#2]
You are Great,  many things works,  Can you tell us how to register new fingerprint.

**Comment by clockkin** [comment]
$role = ($user->user_type == 0) ? 14 : 0; //14= super admin, 0=User :: according to ZKtecho 
                $zk = new CustomLib(); // this is a custom library.The all of method have added here
                $users = $zk->getUser();
                $total = end($users);
                $lastId=$total[3]+1;
                $zk = $zk->setUser($lastId, $user->user_id, $user->name, '1234', $role);
                $up=User::find($user->id);
                $up->increment_id=$lastId;
                $up->save();

**Comment by nurkarim** [comment]
$role = ($user_type == 0) ? 14 : 0; //14= super admin, 0=User :: according to ZKtecho
$zk = new CustomLib(); // this is a custom library.The all of method have added here
$users = $zk->getUser();
$total = end($users);
$lastId=$total[3]+1;
$zk = $zk->setUser($lastId, $user->user_id, $user->name, '1234', $role);
